sudo: required
language: go

go:
  - tip

services:
  - docker

before_install:
  - cd cmd/blog

script:
  - CGO_ENABLED=0 GOOS=linux go build -ldflags "-s" -a -installsuffix cgo -o blog

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=thatsmrtalbot/blog
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
